{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}

{{- if not .Values.cluster.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "milvus.standalone.fullname" . }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
{{ toYaml .Values.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
    component: "standalone"
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
{{ include "milvus.matchLabels" . | indent 6 }}
      component: standalone
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - component
{{- end }}

---
{{- if and .Values.dataNode.enabled .Values.cluster.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "milvus.datanode.fullname" . }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
{{ toYaml .Values.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
    component: "datanode"
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
{{ include "milvus.matchLabels" . | indent 6 }}
      component: datanode
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - component
{{- end }}

---
{{- if and .Values.dataCoordinator.enabled .Values.cluster.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "milvus.datacoord.fullname" . }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
{{ toYaml .Values.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
    component: "datacoord"
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
{{ include "milvus.matchLabels" . | indent 6 }}
      component: datacoord
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - component
{{- end }}

---
{{- if and .Values.indexNode.enabled .Values.cluster.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "milvus.indexnode.fullname" . }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
{{ toYaml .Values.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
    component: "indexnode"
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
{{ include "milvus.matchLabels" . | indent 6 }}
      component: indexnode
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - component
{{- end }}

---
{{- if and .Values.indexCoordinator.enabled .Values.cluster.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "milvus.indexcoord.fullname" . }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
{{ toYaml .Values.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
    component: "indexcoord"
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
{{ include "milvus.matchLabels" . | indent 6 }}
      component: indexcoord
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - component
{{- end }}

---
{{- if and .Values.rootCoordinator.enabled .Values.cluster.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "milvus.rootcoord.fullname" . }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
{{ toYaml .Values.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
    component: "rootcoord"
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
{{ include "milvus.matchLabels" . | indent 6 }}
      component: rootcoord
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - component
{{- end }}

---
{{- if and .Values.proxy.enabled .Values.cluster.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "milvus.proxy.fullname" . }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
{{ toYaml .Values.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
    component: "proxy"
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
{{ include "milvus.matchLabels" . | indent 6 }}
      component: proxy
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - component
{{- end }}

---
{{- if and .Values.queryNode.enabled .Values.cluster.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "milvus.querynode.fullname" . }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
{{ toYaml .Values.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
    component: "querynode"
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
{{ include "milvus.matchLabels" . | indent 6 }}
      component: querynode
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - component
{{- end }}

---
{{- if and .Values.queryCoordinator.enabled .Values.cluster.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "milvus.querycoord.fullname" . }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
{{ toYaml .Values.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
    component: "querycoord"
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
{{ include "milvus.matchLabels" . | indent 6 }}
      component: querycoord
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - component
{{- end }}

{{- end }}